import type { Profile } from "@/types";

export const demoProfiles: Profile[] = [
  {
    id: "demo-alice",
    display_name: "Alice Chen",
    username: "alice",
    bio: "Backend engineer building AI-powered developer tooling and product experiences.",
    city: "Bengaluru",
    locality: "Koramangala",
    linkedin_url: "https://linkedin.com/in/alicechen",
    github_username: "alicechen",
    created_at: "2026-09-01T09:00:00.000Z",
    updated_at: "2026-09-16T06:00:00.000Z",
    headline: "AI & platform engineer",
    role: "ML Engineer",
    rating: 4.8,
    rating_count: 17,
    availability_status: "available",
    distance_km: 3.2,
    skills: ["Python", "FastAPI", "PostgreSQL", "PyTorch", "AWS"],
    interests: ["AI", "Developer Tools", "FinTech"],
    looking_for: ["Frontend", "Product", "UI/UX"],
    github_handle: "@alicechen",
    linkedin_handle: "linkedin.com/in/alicechen",
  },
  {
    id: "demo-bob",
    display_name: "Bob Singh",
    username: "bob",
    bio: "Product-minded frontend engineer who turns ambitious ideas into polished MVP experiences.",
    city: "Bengaluru",
    locality: "Indiranagar",
    linkedin_url: "https://linkedin.com/in/bobsingh",
    github_username: "bobsingh",
    created_at: "2026-08-12T10:00:00.000Z",
    updated_at: "2026-09-16T07:00:00.000Z",
    headline: "Frontend product builder",
    role: "Frontend Engineer",
    rating: 4.6,
    rating_count: 21,
    availability_status: "available",
    distance_km: 2.7,
    skills: ["React", "TypeScript", "Next.js", "Design Systems", "UI/UX"],
    interests: ["Developer Tools", "Open Source", "Education"],
    looking_for: ["Backend", "ML", "Product"],
    github_handle: "@bobsingh",
    linkedin_handle: "linkedin.com/in/bobsingh",
  },
  {
    id: "demo-charlie",
    display_name: "Charlie Nair",
    username: "charlie",
    bio: "Design-driven builder with a strong eye for UX and realistic product execution.",
    city: "Bengaluru",
    locality: "Whitefield",
    linkedin_url: "https://linkedin.com/in/charlienair",
    github_username: "charlienair",
    created_at: "2026-09-03T08:30:00.000Z",
    updated_at: "2026-09-16T07:30:00.000Z",
    headline: "Design + product systems",
    role: "Product Designer",
    rating: 4.9,
    rating_count: 12,
    availability_status: "available",
    distance_km: 6.4,
    skills: ["Figma", "UX Research", "Design Systems", "Prototyping"],
    interests: ["Climate", "HealthTech", "AI"],
    looking_for: ["Frontend", "Product", "Marketing"],
    github_handle: "@charlienair",
    linkedin_handle: "linkedin.com/in/charlienair",
  },
  {
    id: "demo-diana",
    display_name: "Diana Rao",
    username: "diana",
    bio: "Full-stack engineer who enjoys building reliable user-facing systems with clear architecture.",
    city: "Kochi",
    locality: "Fort Kochi",
    linkedin_url: "https://linkedin.com/in/dianarao",
    github_username: "dianarao",
    created_at: "2026-08-21T12:00:00.000Z",
    updated_at: "2026-09-16T05:00:00.000Z",
    headline: "Full-stack product engineer",
    role: "Full Stack Engineer",
    rating: 4.7,
    rating_count: 29,
    availability_status: "available",
    distance_km: 12.5,
    skills: ["Node.js", "TypeScript", "React", "Supabase", "PostgreSQL"],
    interests: ["Open Source", "Education", "Social Impact"],
    looking_for: ["Design", "ML", "Cybersecurity"],
    github_handle: "@dianarao",
    linkedin_handle: "linkedin.com/in/dianarao",
  },
  {
    id: "demo-erin",
    display_name: "Erin Das",
    username: "erin",
    bio: "Security-minded engineer with a strong bias for simple, robust systems and fast feedback loops.",
    city: "Bengaluru",
    locality: "HSR Layout",
    linkedin_url: "https://linkedin.com/in/erindas",
    github_username: "erindas",
    created_at: "2026-09-08T09:45:00.000Z",
    updated_at: "2026-09-15T18:00:00.000Z",
    headline: "Platform & security engineer",
    role: "Security Engineer",
    rating: 4.5,
    rating_count: 14,
    availability_status: "busy",
    distance_km: 4.8,
    skills: ["Go", "Rust", "Security", "Cloud", "DevOps"],
    interests: ["Cybersecurity", "Developer Tools", "Open Source"],
    looking_for: ["Frontend", "Product", "ML"],
    github_handle: "@erindas",
    linkedin_handle: "linkedin.com/in/erindas",
  },
  {
    id: "demo-frank",
    display_name: "Frank Iqbal",
    username: "frank",
    bio: "Systems builder who enjoys solving hard product problems by combining solid engineering with design intuition.",
    city: "Bengaluru",
    locality: "Jayanagar",
    linkedin_url: "https://linkedin.com/in/frankiqbal",
    github_username: "frankiqbal",
    created_at: "2026-08-04T11:15:00.000Z",
    updated_at: "2026-09-10T20:15:00.000Z",
    headline: "Platform systems builder",
    role: "Full Stack Engineer",
    rating: 4.4,
    rating_count: 9,
    availability_status: "unknown",
    distance_km: 8.1,
    skills: ["TypeScript", "Node.js", "DevOps", "Cloud", "Data"],
    interests: ["AI", "Gaming", "Social Impact"],
    looking_for: ["Design", "Product", "Frontend"],
    github_handle: "@frankiqbal",
    linkedin_handle: "linkedin.com/in/frankiqbal",
  },
];
